# Genuine or Fake News Classification Model


## By: Ayush Trivedi

In [1]:
#pip install nltk

Note: you may need to restart the kernel to use updated packages.

The filename, directory name, or volume label syntax is incorrect.

In [2]:
import nltk

In [3]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ayush\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [4]:
import pandas as pd

In [22]:
fake = pd.read_csv(r"C:\Users\ayush\Desktop\Python Code\Fake.csv")
genuine = pd.read_csv(r'C:\Users\ayush\Desktop\Python Code\True.csv')

In [23]:
display(fake.info())
display(genuine.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    21417 non-null  object
 1   text     21417 non-null  object
 2   subject  21417 non-null  object
 3   date     21417 non-null  object
dtypes: object(4)
memory usage: 669.4+ KB

None

In [24]:
display(fake.head())
display(genuine.head())

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [25]:
display(fake.subject.value_counts())
print('\n')
display(genuine.subject.value_counts())

News               9050
politics           6841
left-news          4459
Government News    1570
US_News             783
Middle-east         778
Name: subject, dtype: int64

politicsNews    11272
worldnews       10145
Name: subject, dtype: int64

In [26]:
fake['target'] = 0
genuine['target'] = 1

In [27]:
display(fake.head())

,title,text,subject,date,target
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [28]:
display(genuine.head())

,title,text,subject,date,target
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [29]:
data = pd.concat([fake, genuine], axis=0)

In [30]:
data = data.reset_index(drop=True)

In [31]:
data=data.drop(['subject','date','title'], axis=1)

In [32]:
print(data.columns)
print(data)

Index(['text', 'target'], dtype='object')
                                                    text  target
0      Donald Trump just couldn t wish all Americans ...       0
1      House Intelligence Committee Chairman Devin Nu...       0
2      On Friday, it was revealed that former Milwauk...       0
3      On Christmas day, Donald Trump announced that ...       0
4      Pope Francis used his annual Christmas Day mes...       0
...                                                  ...     ...
44893  BRUSSELS (Reuters) - NATO allies on Tuesday we...       1
44894  LONDON (Reuters) - LexisNexis, a provider of l...       1
44895  MINSK (Reuters) - In the shadow of disused Sov...       1
44896  MOSCOW (Reuters) - Vatican Secretary of State ...       1
44897  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...       1

[44898 rows x 2 columns]

In [34]:
from nltk.tokenize import word_tokenize
data['text']=data['text'].apply(word_tokenize)

In [35]:
print(data.head(10))

                                                text  target
0  [Donald, Trump, just, couldn, t, wish, all, Am...       0
1  [House, Intelligence, Committee, Chairman, Dev...       0
2  [On, Friday, ,, it, was, revealed, that, forme...       0
3  [On, Christmas, day, ,, Donald, Trump, announc...       0
4  [Pope, Francis, used, his, annual, Christmas, ...       0
5  [The, number, of, cases, of, cops, brutalizing...       0
6  [Donald, Trump, spent, a, good, portion, of, h...       0
7  [In, the, wake, of, yet, another, court, decis...       0
8  [Many, people, have, raised, the, alarm, regar...       0
9  [Just, when, you, might, have, thought, we, d,...       0

In [36]:
from nltk.stem.snowball import SnowballStemmer
porter = SnowballStemmer("english", ignore_stopwords=False)

In [37]:
def stem_it(text):
    return [porter.stem(word) for word in text]

In [38]:
data['text']=data['text'].apply(stem_it)

In [39]:
print(data.head(10))

                                                text  target
0  [donald, trump, just, couldn, t, wish, all, am...       0
1  [hous, intellig, committe, chairman, devin, nu...       0
2  [on, friday, ,, it, was, reveal, that, former,...       0
3  [on, christma, day, ,, donald, trump, announc,...       0
4  [pope, franci, use, his, annual, christma, day...       0
5  [the, number, of, case, of, cop, brutal, and, ...       0
6  [donald, trump, spent, a, good, portion, of, h...       0
7  [in, the, wake, of, yet, anoth, court, decis, ...       0
8  [mani, peopl, have, rais, the, alarm, regard, ...       0
9  [just, when, you, might, have, thought, we, d,...       0

In [40]:
#import nltk
#from nltk.corpus import stopwords
#nltk.download('stopwords')
#print(stopwords.words('english'))

In [41]:
def stop_it(t):
    dt = [word for word in t if len(word)>2] 
    return dt

In [42]:
data['text']=data['text'].apply(stop_it)

In [43]:
print(data['text'].head(10))

0    [donald, trump, just, couldn, wish, all, ameri...
1    [hous, intellig, committe, chairman, devin, nu...
2    [friday, was, reveal, that, former, milwauke, ...
3    [christma, day, donald, trump, announc, that, ...
4    [pope, franci, use, his, annual, christma, day...
5    [the, number, case, cop, brutal, and, kill, pe...
6    [donald, trump, spent, good, portion, his, day...
7    [the, wake, yet, anoth, court, decis, that, de...
8    [mani, peopl, have, rais, the, alarm, regard, ...
9    [just, when, you, might, have, thought, get, b...
Name: text, dtype: object

In [44]:
data['text']=data['text'].apply(' '.join)

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data['text'], data['target'], test_size=0.25)
display(X_train.head())
print('\n')
display(y_train.head())

26084    washington reuter presid donald trump son-in-l...
27395    washington reuter u.s. presid donald trump his...
40093    madrid reuter catalonia plan appeal the applic...
17088    oop hillari clinton thought her server was wip...
17750    you can thank obama and all the democrat race ...
Name: text, dtype: object

26084    1
27395    1
40093    1
17088    0
17750    0
Name: target, dtype: int64

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
my_tfidf = TfidfVectorizer( max_df=0.7)

tfidf_train = my_tfidf.fit_transform(X_train)
tfidf_test = my_tfidf.transform(X_test)

In [47]:
print(tfidf_train)

  (0, 87374)	0.10313768982347861
  (0, 8301)	0.045328368477001994
  (0, 63699)	0.10894225800863214
  (0, 83303)	0.1134184851473348
  (0, 65944)	0.06758125627200155
  (0, 1781)	0.07522152053832876
  (0, 27920)	0.06127974446294783
  (0, 69779)	0.07520050283269832
  (0, 33145)	0.08331842442814576
  (0, 63687)	0.11070301755729757
  (0, 73877)	0.12047719121977214
  (0, 66185)	0.09200945556024553
  (0, 7779)	0.09496391546814642
  (0, 17319)	0.07807060538795388
  (0, 32154)	0.10813361652265102
  (0, 33859)	0.08331121886383047
  (0, 71829)	0.1733402899458372
  (0, 69472)	0.1253221411898916
  (0, 38218)	0.03558026554834306
  (0, 22085)	0.21730104742664125
  (0, 41508)	0.15683131893461696
  (0, 37366)	0.08958245241925691
  (0, 21874)	0.0784493089393442
  (0, 54032)	0.06804997491763354
  (0, 53844)	0.07365151433620913
  :	:
  (33672, 17965)	0.06704544086607482
  (33672, 74879)	0.12082237141653716
  (33672, 72726)	0.0856232258700286
  (33672, 7863)	0.0767530014042981
  (33672, 29415)	0.14544170108332583
  (33672, 77999)	0.054629232516588265
  (33672, 61754)	0.0931168092433639
  (33672, 63597)	0.031481681330654245
  (33672, 25218)	0.03905427778758872
  (33672, 61898)	0.033204099180513244
  (33672, 17788)	0.07146894160111528
  (33672, 50596)	0.0478721237147349
  (33672, 80391)	0.04664181936929954
  (33672, 79517)	0.07527691968876755
  (33672, 28839)	0.03797847631744571
  (33672, 8337)	0.037597704131413445
  (33672, 89301)	0.031753693557747084
  (33672, 84443)	0.17587940185179207
  (33672, 38218)	0.02356546287933939
  (33672, 54032)	0.045070747313074755
  (33672, 39381)	0.025960334519949627
  (33672, 59623)	0.047133897360991876
  (33672, 41550)	0.052655551733382634
  (33672, 83809)	0.26160536776900783
  (33672, 27014)	0.16064715004288807

In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [49]:
model_1 = LogisticRegression(max_iter=900)
model_1.fit(tfidf_train, y_train)
pred_1 = model_1.predict(tfidf_test)
cr1    = accuracy_score(y_test,pred_1)
print(cr1*100)

98.8596881959911

In [50]:
from sklearn.linear_model import PassiveAggressiveClassifier

model = PassiveAggressiveClassifier(max_iter=50)
model.fit(tfidf_train, y_train)

PassiveAggressiveClassifier(max_iter=50)

In [51]:
y_pred = model.predict(tfidf_test)
accscore = accuracy_score(y_test, y_pred)
print('The accuracy of prediction is ',accscore*100)

The accuracy of prediction is  99.64365256124722